### PR TITLE
Add TypeScript module definition

### PR DESCRIPTION
**Pull request by jmalonzo**

### CODE REVIEW

**Comment by SamVerschueren** [comment]
Sorry, it's better to publish them to DefinitelyTyped https://github.com/sindresorhus/ama/issues/439

**Comment by jmalonzo** [comment]
*sigh* thanks anyway

**Comment by SamVerschueren** [comment]
Not everyone cares about TypeScript so it's not up to the module maintainer to maintain the definitions if he doesn't use it himself. It's only overhead.

**Comment by jmalonzo** [comment]
It's a function with a couple of params, but yeah sure I'll keep that in mind in the future (and not all contributors fire and forget).

**Comment by sindresorhus** [comment]
I now accept TypeScript definitions if anyone looking is interested in submitting.

See: https://github.com/sindresorhus/ama/issues/439#issuecomment-414212229

Please follow this guide: https://github.com/sindresorhus/typescript-definition-style-guide

**Pull request closed without merging**
