### PR TITLE
Prefix trimming

### PR DESCRIPTION
**Pull request by Yomguithereal**
Hello @sindresorhus. I just implemented the prefix trimming optimization on your function. However, on my benchmark, the benefit is not that clear cut (benchmark's examples may not be perfectly suited to see the advantages of this optimization maybe).

So I'll let you decide whether you want to merge this or not.

Have a good day.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Nice!

Benchmarks looks good (Node.js 7.5.0).


## master


```
         401,487 op/s » leven
         371,707 op/s » talisman
         264,191 op/s » levenshtein-edit-distance
         152,923 op/s » fast-levenshtein
          57,267 op/s » levenshtein-component
          19,915 op/s » levdist
          21,802 op/s » ld
          18,079 op/s » natural
          11,761 op/s » levenshtein
```


## This PR

```
         448,206 op/s » leven
         362,329 op/s » talisman
         276,395 op/s » levenshtein-edit-distance
         146,641 op/s » fast-levenshtein
          61,061 op/s » levenshtein-component
          20,720 op/s » levdist
          22,642 op/s » ld
          18,966 op/s » natural
          11,623 op/s » levenshtein
```

Although `talisman` seems to have regressed slightly. My fixtures/benchmarks might not be optimal. Help welcome to make them more realistic.

**Comment by Yomguithereal** [comment]
How many times did you run the benchmarks? On my computer, they tend to differ a lot sometimes.

**Comment by sindresorhus** [comment]
Multiple times, but now I get slightly different results, so results are not very stable.

```
         439,409 op/s » leven
         384,934 op/s » talisman
         284,955 op/s » levenshtein-edit-distance
         161,983 op/s » fast-levenshtein
          59,220 op/s » levenshtein-component
          20,824 op/s » levdist
          23,470 op/s » ld
          20,145 op/s » natural
          12,604 op/s » levenshtein
```

**Comment by Yomguithereal** [comment]
Yes. I guess this is the fun of benchmarking JavaScript :).Do you know if `matcha` interleaves the tests and/or run them in separate threads each time?

Another solution to compare would be to copy the old `leven` function and incorporate it to the benchmark. What do you think?

**Comment by Yomguithereal** [comment]
I've pushed a branch [here](https://github.com/sindresorhus/leven/tree/benchmark-old-leven) to play with the idea.

**Comment by Yomguithereal** [comment]
And this:

```js
fn('bbbbbbackkkkkk', 'bbbbbbookkkkkk');
```

is a caricatural benchmark case if you want to see benefits of the trimming optimizations.

**Comment by syzer** [comment]
awesome!

**Comment by sindresorhus** [comment]
> Do you know if matcha interleaves the tests and/or run them in separate threads each time?

It runs them serially in the same process. We can try increasing `set('mintime', 500);` and `set('delay', 100);` and see if it helps.

**Comment by sindresorhus** [comment]
> Another solution to compare would be to copy the old leven function and incorporate it to the benchmark. What do you think?

Yes, that's a good idea. We can just depend on the previous version through a git tag: `npm i --save-dev sindresorhus/leven#v2.0.0`

**Comment by sindresorhus** [comment]
This looks great. Thank you! :)

**Pull request merged**
